AB/blog/blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('blog_app.urls', namespace='posts')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AB/blog/blog_app/urls.py
from django.urls import path

from .views import post_list,post_details,post_create,post_update,post_delete

app_name = 'blog_app'
urlpatterns = [
    path('',post_list, name='post_list'),
    # path('details/<int:pk>/',post_details, name='post_details'),
    path('details/<slug:slug>/',post_details, name='post_details'),
    path('create/',post_create, name='post_create'),
    path('update/<int:id>/',post_update, name='post_update'),
    path('delete/<int:id>/',post_delete, name='post_delete')
]

AB/blog/blog_app/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save
from django.shortcuts import reverse
from django.utils import timezone
from django.utils.text import slugify




class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager,self).filter(draft=False).filter(publish__lte=timezone.now())

def upload_location(instance,filename):
    return "%s/%s" %(instance.id, filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    content = models.TextField()
    image = models.ImageField(upload_to=upload_location, null=True, blank=True, height_field='height_field', width_field='width_field')
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    slug = models.SlugField(unique=True)
    draft = models.BooleanField(default=False) #added in ch-35
    publish = models.DateTimeField() #added in ch-35

    objects = PostManager()


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:post_details', kwargs={'slug':self.slug}) #changed from pk to slug for slug field
        # return "post/details/%s/" %(self.pk)

    
    # class Meta:
    #     ordering = ['-timestamp', '-updated']




def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    print(slug)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    # print('test1- ',qs.first().id)
    exists = qs.exists()
    if exists:
        print('2nd - ',slug)
        new_slug = "%s-%s" %(slug, qs.last().id)
        return create_slug(instance,new_slug=new_slug)
    return slug



def pre_save_post_reciever(sender,instance,*args,**kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_post_reciever,sender=Post)

AB/blog/comments/models.py
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey # This is added in generic foriegnkey part-2
from django.contrib.contenttypes.models import ContentType

from django.db import models

from blog_app.models import Post



class Comments(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
    # post = models.ForeignKey(Post, on_delete=models.CASCADE) 

    # This is added in generic foriegnkey part-2
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user.username)

AB/blog/blog_app/forms.py
from django import forms

from pagedown.widgets import PagedownWidget


from .models import Post




class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget) # Added in AD - 4
    publish = forms.DateField(widget=forms.SelectDateWidget) # Added in AD - 4
    class Meta:
        model = Post
        fields = [
            'title',
            'user',
            'content',
            'image',
            'draft',
            'publish',
            
        ]

AB/blog/blog_app/views.py
from urllib.parse import quote_plus
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponseRedirect,Http404
from django.shortcuts import render,get_object_or_404,redirect
from django.utils import timezone


from .models import Post
from .forms import PostForm

def post_list(request):
    # the below line is alternative for model Manager but not suitable at every time
    # queryset = Post.objects.filter(draft=False).filter(publish__lte=timezone.now()) #all().order_by('-id') #.order_by('-timestamp')
    today = timezone.now()
    queryset = Post.objects.active() # added in ch-36
    if request.user.is_staff or request.user.is_superuser: # added in ch-36
        queryset = Post.objects.all() # added in ch-36

    query = request.GET.get('q')
    if query:
        queryset = Post.objects.filter(
            Q(title__icontains=query)|
            Q(content__icontains=query)|
            Q(user__first_name__icontains=query)|
            Q(user__last_name__icontains=query)).filter(draft=False).distinct()

    paginator = Paginator(queryset, 5) # Show 5 contents per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'object_list' : page_obj,
        'page_obj': page_obj,
        'today':today
    }
    return render(request,'blog_app/post_list.html',context)


def post_details(request,slug = None, pk=None):
    # instance = get_object_or_404(Post,pk=pk)
    instance = get_object_or_404(Post,slug=slug)
    if instance.draft or instance.publish > timezone.now():
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    share_string = quote_plus(instance.content)
    context = {
        'obj_details':instance,
        'share_string':share_string
    }
    return render(request,'blog_app/post_details.html',context)


def post_create(request):
    # if not request.user.is_staff or not request.user.is_supperuser:
        # raise Http404

    # if not request.user.is_authenticated:
    #     raise Http404

    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request,'Succesfuly created')
        return HttpResponseRedirect(instance.get_absolute_url())
    # else:
    #     messages.error(request,'Not succesfully created')    
    context = {
        'form':form
    }
    return render(request, 'blog_app/post_create.html',context)



def post_update(request, id=None):
    # if not request.user.is_staff or not request.user.is_supperuser:
    #     raise Http404

    # if not request.user.is_authenticated:
    #     raise Http404
    
    instance = get_object_or_404(Post,id=id) #This instance should pass through form to update
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request,'<a href="">Item</a> Succesfuly changed',extra_tags='html_safe') #extra tag is used to create different classes in html
        return HttpResponseRedirect(instance.get_absolute_url()) #redirecting the url is must and should once after saved the form
    # else:
    #     messages.error(request,'Not succesfully changed')

    context = {
        'form':form
    }
    return render(request, 'blog_app/post_create.html',context)


def post_delete(request,id=None):
    if not request.user.is_staff or not request.user.is_supperuser:
        raise Http404
    instance = get_object_or_404(Post,id=id)
    instance.delete()
    messages.success(request, "Succesfully deleted")
    return redirect('blog_app:post_list')

AB/blog/comments/views.py
from django.shortcuts import render

# Create your views here.

AB/blog/blog_app/templates/blog_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>
        {% block head_title %}
        TD 1.9
        {% endblock head_title %}
    </title>

    {% block head_extra %}  {% endblock head_extra %} <!-- Added in AD -4 -->
</head>

<body>
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous"
        src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v6.0&appId=404146670258426&autoLogAppEvents=1"></script>

    {% include 'blog_app/messages.html' %}
    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>

</body>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>

<!-- <script src="https://code.jquery.com/jquery-3.5.0.min.js"
    integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script> -->

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/1.0.0/marked.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $(".content-markdown").each(function () {
            var content = $(".content-markdown").text()
            console.log(content)
            console.log('test here')
            var markedContent = marked(content)
            console.log(markedContent)
            $(this).html(markedContent)
            
        })

        // $(".content-markdown img").each(function () {  // img is looking for the image tagwith parent class or matching class with the mark-down class
        //     $(this).addClass('img-responsive')
            
        // })


    })
</script>

</html>

AB/blog/blog_app/templates/blog_app/messages.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if messages %}
    <div class="messages">

        <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                {% if "html_safe" in message.tags %}
                {{ message|safe }}
                {% else %}
                {{ message }}
                {% endif %}
            </li>
            {% endfor %}
        </ul>

    </div>
    {% endif %}
</body>
</html>

AB/blog/blog_app/templates/blog_app/post_create.html
{% extends 'blog_app/base.html' %}

{% load crispy_forms_tags %} <!--This is for crispy form-->

{% block head_extra %}
{{form.media}}
<!-- Added in AD - 4 --->

{% endblock head_extra %}

{% block content %}
<div class="row">
<div class="col-sm-6">
    <h1>Preview</h1>
    <div class="content-preview">
        <h3 id='preview_title'></h3>
        <p id="preview_content"></p>
    </div>
</div>
<div class="col-sm-6 offset-6" >
    <h1>Form</h1>
    <form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
        {{form|crispy}}
        <input type="submit" value="Submit">
    </form>
</div>
</div>
{% endblock content %}

AB/blog/blog_app/templates/blog_app/post_details.html
{% extends 'blog_app/base.html' %}
{% load urlify %}

{% block head_title %}
{{obj_details.title}} | {{block.super}}
{% endblock head_title %}

{% block content %}
<div class="col-md-7 offset-md-3">
    <h1>{{obj_details.title}}</h1><small>Posted {{obj_details.timestamp|timesince}} ago &nbsp;&nbsp;
        {% if obj_details.draft %}
        <span style="color: red;" ><strong>Draft</strong></span>
        {% endif %}
     </small><br>
    <!--added timesince here-->
    {% if obj_details.image %}
    <img src="{{ obj_details.image.url }}" class="img-responsive">
    {% endif %}
    <div class="col-md-12 content-markdown">
    <p>{{obj_details.content}}</p><br><br><br>
    <hr/>
    </div>
    <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-width="" data-layout="standard"
        data-action="like" data-size="small" data-share="true"></div>
    <hr/>

    <div>
        {{obj_details.comments_set.all}} <!--Added in generic foriegn key part1-->
    </div>

    <div class="fb-comments" data-href="{{request.build_absolute_uri}}" data-numposts="5" data-width=""></div>
    <hr/>
    <!-- {{obj_details.content|urlify}} <br> -->


    <!-- add the absolute uri as below -->
    <a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}">
        Facebook
    </a>|

    <a href="https://twitter.com/home?status={{share_string}}%20{{request.build_absolute_uri}}/">
        Twitter
    </a>|

    <a
        href="https://www.linkedin.com/shareArticle?mini=true&url={{request.build_absolute_uri}}/&title={{request.build_absolute_uri}}&source={{request.build_absolute_uri}}">
        Linkedin
    </a>|


    <a href="http://www.reddit.com/submit?url={{request.build_absolute_uri}}&title={{share_string}}">Share on Reddit</a>

</div>



{% endblock content %}

AB/blog/blog_app/templates/blog_app/post_list.html
{% extends 'blog_app/base.html' %}


{% block content %}
<h1>Heading for test</h1>
<div class="col-sm-8 offset-2">
    <div>
        <form method="GET" action="">
            <div class="input-group">
                <input type="text" name="q" placeholder="Type here">
                <span class="input-group-btn">
                <!-- <input type="submit" value="Submit" /> -->
                <button class="btn btn-info" type="submit"><i class="fa fa-search"></i></button>
                </span>
                
            </div>
        </form><br><br>
    </div>

    {% for obj in object_list %}
    <div class="col-sm-6">
        <div class="card" style="width: 30rem;">
            {% if obj.image %}
            <img src="{{obj.image.url}}" class="card-img-top" alt="...">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title">{{obj.title}} {% if obj.draft %} <span style="color: red;">- Draft</span>
                    {% endif %} </h5><br>
                <h5> {% if obj.publish > today %} <strong>Future Posts</strong> {% endif %} </h5>
                <p>id : {{obj.id}}</p>
                <!-- <p>{{obj.slug}}</p> -->
                <p class="card-text content-markdown">{{obj.content}}</p>
                <a href="{% url 'posts:post_details' slug=obj.slug %}" class="btn btn-primary">View</a>
            </div>
        </div><br><br>
    </div>



    <!--dynamic url added-->
    {% endfor %}

</div>
</div>


<span><br></span>
{% for obj in object_list %}
<!-- <a href="{{ obj.get_absolute_url }}"><strong>{{obj.title}}</strong></a><br> -->

<!-- 2nd method  -->
{% endfor %}

</div>


<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{request.GET.q}}
            {% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>


{% endblock content %}